apiVersion: 1

datasources:
  - name: MySQL-CarbonDB
    type: mysql
    url: mysql:3306
    database: carbon_db
    user: grafana_user
    secureJsonData:
      password: GrafanaPass@2024
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: false
